services:
  postgis:
    image: postgis/postgis:18-3.6
    environment:
      POSTGRES_DB: geoai_db
      POSTGRES_USER: geoai
      POSTGRES_PASSWORD: geoai
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./database/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: https://gis-2-erng.onrender.com
    ports:
      - "5173:80"

volumes:
  postgis_data:
